apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapplication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleapp-webapp
      version: v1
  template:
    metadata:
      labels:
        app: simpleapp-webapp
        version: v1
    spec:
      containers:
        - name: simpleapp-webapp
          image: armansk9129/cloudethix_initcontainer_arman:v1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      initContainers:
        - name: install
          image: busybox:1.28
          command:
            - wget
            - "-O"
            - "/work-dir/index.html"
            - http://info.cern.ch
          volumeMounts:
            - name: workdir
              mountPath: "/work-dir"
      volumes:
        - name: html-volume
          emptyDir: {}
        - name: workdir
          emptyDir: {}

