apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: myapplication
spec: 
  replicas: 2 
  selector: 
    matchLabels:
      app: simpleapp-webapp
      version: v1 
  template: 
    metadata: 
      labels: 
        app: simpleapp-webapp
        version: v1
    spec: 
      containers: 
        - name: simpleapp-webapp
          image: armansk9129/cloudethix_initcontainer_arman:v1
          ports:
            - containerPort: 80

