apiVersion: v1
kind: Service
metadata:
  name: simpleapp
spec:
  type: NodePort
  selector:
    app: simpleapp-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30020
